version: "3.3"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - /root/backend-backup/data:/data
      - /root/backend-backup/backups:/backups
    container_name: mongo-db

  redis:
    image: redis
    ports:
      - 6377:6379
    restart: always
    container_name: redis

  backendContainer:
    image: backend-image
    restart: always
    ports:
      - 8080:8080
    container_name: BackendContainer
    environment:
      ENV: production
      PORT: 3000
      TZ: "Asia/Bangkok"